apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appdeployd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ljovel/v1.git
    targetRevision: HEAD
    path: master
  destination: 
    server: https://kubernetes.default.svc
    namespace: appDeployd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true