apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployd
  labels:
    app: web
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: appdeployd
        image: 19930501/deployd-k8s:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 64Mi
            cpu: 30m