apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: hello-pod
        image: 19930501/deployd-k8s:1.1
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 64Mi
            cpu: 30m