apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployd
spec:
  selector:
    matchLabels:
      app: appdeployd
  replicas: 6
  template:
    metadata:
      labels:
        app: appdeployd
    spec:
      containers:
      - name: appdeployd
        image: 19930501/deployd-k8s:1.1
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 64Mi
            cpu: 30m