apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  selector:
    app: web-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
